### ISSUE TITLE
使用统一的 Tag 类型以方便读取 tag

### ISSUE THREAD

**Issue by Ferry-200** [chanmaoganda/NcmDumpLib#1]
很抱歉多次打扰。这次在这里提 issue 而不是继续在 https://github.com/Ferry-200/coriander_player/issues/58 讨论，是因为我觉得在这里应该更合适。

现在 NcmMusic 的定义如下：
```rust
/// Stores music data extracted from an NCM file.
pub struct NcmMusic {
    pub metadata: Box<dyn MetaData>,
    pub audio_data: Vec<u8>,
    pub music_type: String,
}
```
其中 metadata 是 `Box<dyn MetaData>` 类型。虽然 `Mp3MetaData` 和 `FlacMetadata` 都实现了 `Metadata` trait，但是 rust 的 trait 似乎和我理解的 interface 不太一样——不可以直接使用 as 进行类型转换。所以我不清楚怎样访问具体类型的 metadata。或者 rust 有什么我不知道的手段做到这一点？

我询问过 gpt，它给出的解决方案是让 MetaData 继承 Any 类型。可是直接修改 crate 并自己维护一份似乎也不是好的做法。

所以我想问，可不可以在 MetaData 里面增加一个统一类型的 Tag 字段以方便读取不同格式的 tag（id3 和 vorbis comment），这样就不需要访问到具体的 `Mp3MetaData` 或 `FlacMetadata` 类型（？）。如果不想自己处理这些，我推荐 [lofty](https://crates.io/crates/lofty) 的 [`Tag`](https://docs.rs/lofty/0.21.0/lofty/tag/struct.Tag.html) 类型，这个 crate 支持很多类型的 tag。这样你这个库也就不需要自己实现 NcmInfo 这个类型了。不过可能这个 crate 对于 NcmDumpLib 来说太大了。

**Comment by chanmaoganda** [comment]
我设计的时候就只是为了让他可以注入, 并没有设计成lofty那种的tag, 我考虑过用lofty, 不过确实对于这个crate来说有些大, 当时没用lofty就是考虑到没有必要用这么全功能的crate, rust的trait只能定义行为, 我觉得可以重写一份, 直接做一个新的crate?

**Comment by Ferry-200** [comment]
只要你不觉得麻烦就好😂

**Comment by chanmaoganda** [comment]
或者做个新的feature?

**Comment by Ferry-200** [comment]
由你做决定吧，我在这方面不是很了解。

**Comment by chanmaoganda** [comment]
现在拉0.2.0的版本就可以了, 直接重新用lofty的tag取代id3的tag了

**Comment by Ferry-200** [comment]
好好好

**Comment by Ferry-200** [comment]
>https://docs.rs/lofty/latest/lofty/flac/struct.FlacFile.html#notes

> The ID3v2 tag is read only, and it’s use is discouraged by spec

flac 应该用 vorbis comment 才是更规范的吧？不过这样也行，改不改都可以。
